import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/NavBar";
import { Outfit } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const outfit = Outfit({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* <link href="https://api.fontshare.com/v2/css?f[]=general-sans@200,201,300,301,400,401,500,501,600,601,700,701,1,2&display=swap" rel="stylesheet"/> */}
      </head>
      <body className={outfit.className}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
